### PR TITLE
AOSP support

### PR DESCRIPTION
**Pull request by nkh-lab**
Add Android.bp build script.

Signed-off-by: Nikolay Khilyuk <nkh@ua.fm>

### CODE REVIEW

**Comment by scmikezhang** [comment]
Are u doing SOME/IP project under Andorid now?Can I ask u some relative questions about this?If so ,how can I contact u? Thx~

**Comment by nkh-lab** [comment]
Hi @scmikezhang 

> Are u doing SOME/IP project under Andorid now?Can I ask u some relative questions about this?If so ,how can I contact u? Thx~

Yes, now I have all worked CommonAPI via SOME/IP (CommonAPI-SOMEIP and vSOMEIP) stuff on my AOSP project (tested on HiKey960 for Android Q code-base). All required changes were provided like pull-requests for mentioned GENIVI projects.

For contacting you can use my e-mail: nkh@ua.fm

**Comment by gunnarx** [comment]
Apologies for hijacking the PR thread for a while.

>Yes, now I have all worked CommonAPI via SOME/IP (CommonAPI-SOMEIP and vSOMEIP) 
> stuff on my AOSP project (tested on HiKey960 for Android Q code-base). 
> All required changes were provided like pull-requests for mentioned GENIVI projects.
> For contacting you can use my e-mail: nkh@ua.fm

@scmikezhang @nkh-lab This is indeed of general interest.  GENIVI even runs a special interest group for Android adopters in Automotive, and the inclusion of these technologies are becoming important for several companies.  For that reason, I would ask if it's possible for you to keep the conversation public instead.

If it is related to components, it is fine to do it on each component like you have.

If it is general, we can have the conversation at this repository:
https://github.com/GENIVI/aasig_dev_platform
or with mailing lists or other methods (we also have open phone meetings For the AA-SIG).

(If you do not know me I am the Development Lead for the GENIVI Alliance.  I would be happy to set up the needed support to make this a more shared collaboration and support you in other ways.)

**Comment by nkh-lab** [comment]
Hi @gunnarx 

> If it is general, we can have the conversation at this repository:
https://github.com/GENIVI/aasig_dev_platform
or with mailing lists or other methods (we also have open phone meetings For the AA-SIG).

Let's try discuss the details directly in email. Thanks.

**Comment by nkh-lab** [comment]
Already in v3.2.0.

**Pull request closed without merging**
